name: PARL Unittest
on: 
  pull_request:
    branches:
    - develop

jobs:
  CheckStyle:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Check Style
        run: |
          ls ..
          pwd
          ls
          cat .github/workflows/*.yml
          bash .teamcity/action_build.sh check_style

