name: CI for PARL
on: 
  pull_request:
    branches:
    - develop

jobs:
  ci:
    name: Unit-Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Build Docker Image
        uses: docker://docker:stable

      - name: Build Docker image
        run: |
          ls
          pwd
          md5sum Dockerfile |cut -d' ' -f1|xargs echo md5=
          docker build -t parltestimage -f .teamcity/DOCKERFILE .

      - name: Run tests
        run: |
          ls
          pwd
          cat .github/workflows/develop.yml
          docker run parltestimage .teamcity/build.sh test
