name: Test
on: 
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  my-job:
    name: Greeting for PARL
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: PaddlePaddle
        MIDDLE_NAME: Reinforement
        LAST_NAME: Learning
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
