name: PARL Unittest
on: 
  pull_request:
    branches:
    - develop

jobs:

  UnitTest:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Package
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          sudo apt-get install -y libgflags-dev libunwind-dev libgoogle-glog-dev libomp-dev unzip
          sudo apt-get install -y libgtest-dev && cd /usr/src/gtest && sudo mkdir build && cd build && sudo cmake .. && sudo make && ls -l /usr/src/googletest/googletest/build && sudo cp /usr/src/googletest/googletest/build/libgtest*.a /usr/local/lib

      - name: Run Paddle tests
        run: |
          bash .teamcity/action_build.sh test_paddle
